name: Lint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set node version and build
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint
